# To use:
#
#   $ conda env create -f environment.yml
#   $ conda activate nweng-dev
#
name: nweng-dev
channels:
  - conda-forge
dependencies:
  - python=3.12 
  - cython>=3.0
  - compilers
  - ninja
  - meson-python
  - pip
  - numpy
  - build
  - spin
  # # For testing
  # - pytest
  # - pytest-cov
  # - pytest-xdist
  # - hypothesis
  # For type annotations
  - mypy
  # # For building docs
  # - sphinx>=4.5.0
  # - sphinx-design
  # - numpydoc=1.4.0
  # - ipython
  # - scipy
  # - pandas
  # - matplotlib
  # - pydata-sphinx-theme=0.13.3
  # - doxygen
  # # NOTE: breathe 4.33.0 collides with sphinx.ext.graphviz
  # - breathe>4.33.0
  # For linting
  - pycodestyle=2.7.0
  - gitpython
  # # Used in some tests
  # - cffi
  # - pytz